almacenar los registros en la base de datos
jose-1991/proyecto1 pull request #5
Opened 2021-12-07 17:22 UTC by jose-1991

2021-12-08 15:21 UTC, trevifergloria requested changes
optimizer quitarDuplicadoProducto()  & quitarDuplicadoCustomer() metodos

2021-12-08 19:40 UTC, trevifergloria requested changes
todavia se puede optimizar, eliminar el metodo `asignarId`

2021-12-13 15:29 UTC, trevifergloria requested changes

2021-12-13 15:29 UTC, trevifergloria commented on src/main/java/org/jflores/proyect/UserStore.java
> +        dataBase.listToMysql("INSERT INTO store.order(order_ID, orderDate, customer_ID, address_ID, product_ID, price, quantity, discount, total, profit)" +
revisa como utilizar ENUMS en vez de strings en el argumento del metodo listToMySql

2021-12-13 15:29 UTC, trevifergloria commented on src/main/java/org/jflores/proyect/DataBase.java
> +            }
que es esto?

2021-12-13 15:29 UTC, trevifergloria commented on src/main/java/org/jflores/proyect/DataBase.java
> +            getConnection().setAutoCommit(false);
para que este set? si después lo cambias a true?

2021-12-13 15:35 UTC, jose-1991 commented on src/main/java/org/jflores/proyect/DataBase.java
> +            getConnection().setAutoCommit(false);
es para hacer el rollback en caso de falla, ademas mejora el tiempo de ejecucion a  3seg,  y sin el set es un poco mas de 1 min..

2021-12-13 15:35 UTC, jose-1991 commented on src/main/java/org/jflores/proyect/DataBase.java
> +            }
hace un rollback  en caso que de falla..

2021-12-22 21:32 UTC, trevifergloria approved these changes

2021-12-22 21:36 UTC, merged